[package]
name = "rutils"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.28.0", features = ["user"] }

[[bin]]
name = "cat"
path = "src/cat.rs"

[[bin]]
name = "ls"
path = "src/ls.rs"
